cdi-rs: Rename JSONSchema
With jsonschema v0.21.0 we get the error:
```
error[E0412]: cannot find type `JSONSchema` in crate `jsonschema`
```
this is because the struct was renamed to Validator in
[v0.20.0](https://github.com/Stranger6667/jsonschema/releases/tag/rust-v0.20.0)
so update this reference along with the jsonschema version bump

Signed-off-by: stevenhorsman <steven@uk.ibm.com>